### ISSUE TITLE
cumm and spconv versions do not match

### ISSUE THREAD

**Issue by BlackNightdd** [FindDefinition/cumm#28]
I encountered the following error while installing spconv.
ERROR: Could not find a version that satisfies the requirement cumm<0.5.0,>=0.4.5 (from spconv) (from versions: 0.1.0, 0.5.0, 0.5.1, 0.5.3, 0.6.0, 0.6.1, 0.6.2, 0.6.3)
ERROR: No matching distribution found for cumm<0.5.0,>=0.4.5
I don't know how to solve it?

**Comment by xiaohuang2004** [comment]
What platform do you use? It should have versions >=0.45 and <0.5

**Comment by BlackNightdd** [comment]
> 您使用什么平台？它应具有版本 >=0.45 和 <0.5

Thank you, because my CUDA and Python versions are too high, and the error says that there are only versions 0.1.0, 0.5.0, 0.5.1, 0.5.3, 0.6.0, 0.6.1, 0.6.2, 0.6.3, which do not meet the requirements of>=0.45 and<0.5. After reinstalling the lower versions of CUDA and Python, the issue was resolved.

**Comment by ifilipis** [comment]
I'd like to open this one. 

Seems like none of the versions of cumm work with Python 3.12. 

The error I'm getting
  File "E:\tmp\spconv\setup.py", line 154, in <module>
    from cumm.gemm.main import GemmMainUnitTest
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cumm\gemm\main.py", line 30, in <module>
    from cumm import tensorview as tv
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cumm\tensorview\__init__.py", line 27, in <module>
    from cumm.core_cc import tensorview_bind
ImportError: DLL load failed while importing core_cc: The specified module could not be found.

Happens on any version, both when installed from pip and compiled from source with CUMM_DISABLE_JIT=1

I also tried to compile with CUMM_DISABLE_JIT=0, but it has some weird linker error (uses x86 compiler instead of x64), even though I use the correct VC environment

On lower Python it works and starts just fine, but I have to use 3.12 and can't downgrade
